services:
  app:
    build: .
    container_name: app-python
    restart: always
    network_mode: host
    pid: host

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - USUARIO_ADMIN=${USUARIO_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}

    volumes:
      - /:/host:ro